repos:
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: cargo-check
  # - repo: local
  #   hooks:
  #     - id: clippy-fix
  #       name: cargo clippy --fix
  #       entry: cargo clippy --fix --allow-dirty --allow-staged
  #       language: system
  #       pass_filenames: false
  #       types: [rust]
