[project]
name = "heisenbase-scripts"
version = "0.1.0"
description = "uv environment for helper scripts for heisenbase"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.18.4",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
]
